CREATE TABLE LGUIDE_INFO (
Lguide_id	VARCHAR(20) NOT NULL,
Lguide_name VARCHAR(20) NOT NULL,
Lguide_phone VARCHAR(20) NOT NULL,
)
DROP TABLE LGUIDE_INFO
INSERT INTO LGUIDE_INFO (Lguide_id,Lguide_name,Lguide_phone) VALUES ('9001','XYZ','01734132221')