CREATE TABLE SPOT_INFO (
SPOT_NAME VARCHAR(20) NOT NULL,
SPOT_CODE VARCHAR(20) NOT NULL,
)
DROP TABLE SPOT_INFO
INSERT INTO SPOT_INFO (SPOT_CODE,SPOT_NAME) VALUES ('SAJEK','SP1')
INSERT INTO SPOT_INFO (SPOT_CODE,SPOT_NAME) VALUES ('BANDARBAN','SP2')
INSERT INTO SPOT_INFO (SPOT_CODE,SPOT_NAME) VALUES ('SUNAMGANJ','SP3')
INSERT INTO SPOT_INFO (SPOT_CODE,SPOT_NAME) VALUES ('COXS BAZAR','SP4')
INSERT INTO SPOT_INFO (SPOT_CODE,SPOT_NAME) VALUES ('SYLHET','SP5')

