CREATE TABLE TRANSPORT_INFO (
SPOT_CODE  VARCHAR(20) NOT NULL,
H_ac INT,
H_nac INT ,
E_ac INT ,
E_nac INT ,
S_ac INT,
S_nac  INT 
)

INSERT INTO TRANSPORT_INFO(SPOT_CODE,H_ac,H_nac,E_ac,E_nac,S_ac,S_nac) VALUES ('SP1',1500,800,1500,800,1500,800)